### ISSUE TITLE
Adjust + Button Position

### ISSUE THREAD

**Issue by m7real** [Sunkio/video-bookmarker#8]
The + sign in the player makes other buttons on the right side are going out of sight, can you please fix it?

**Comment by Sunkio** [comment]
Thanks for reaching out! I'll check it and get back to you if I need more info or when I've fixed the issue. :)

**Comment by Sunkio** [comment]
Fixed it, and the updated version is now published in the Chrome Web Store.
I'm closing this issue now. Thanks again for raising it, this was very helpful!

**Comment by Sunkio** [comment]
Closed :)
